spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: alex
    password: vfqrf19
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

